---
- name: break easytravel demo
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    - dt_easytravel_url: http://rh-dynatrace-08.cool.lab:8091
  tasks:
    - name: call easytravel API to break purchase button
      ansible.builtin.uri:
        url: '{{ dt_easytravel_url }}/services/ConfigurationService/setPluginEnabled?name=CreditCardCheck&enabled=true'
        return_content: true
        status_code: 202
      register: url_return
    - name: print result
      debug:
        var: url_return
