---
-
  hosts: localhost
  name: "Remediate CPU saturation"
  tasks:
    - name: Print Dynatrace ProblemId
      debug:
        msg: "{{ansible_eda.event.payload.eventId}}"
      when: ansible_eda.event.payload.problemStatus == "OPEN"

    - name: Post comment to Dynatrace - triggered playbook
      shell: "curl -X POST --header 'Authorization: Api-Token {{dynatrace_api_token}}' -H 'Content-Type: application/json' -d '{\"message\": \"Ansible EDA controller-Triggered Ansible playbook to resolve CPU problem\"}' {{dynatrace_api_url}}/api/v2/problems/{{ansible_eda.event.payload.eventId}}/comments"
      when: ansible_eda.event.payload.problemStatus == "OPEN"

    -
      name: "Remediate CPU saturation issue"
      block:
        -
          name: "call easytravel configuration UI to apply configuration change"
          uri:
            url: "http://{{ easytravel_host }}:8079/services/ConfigurationService/setPluginEnabled?name={{ easytravel_plugin }}&enabled={{ easytravel_plugin_state }}"
            status_code: 202

    - name: Post comment to Dynatrace - playbook ran successfully
      shell: "curl -X POST --header 'Authorization: Api-Token {{dynatrace_api_token}}' -H 'Content-Type: application/json' -d '{\"message\": \"Ansible EDA controller-Successfully ran Ansible playbook\"}' {{dynatrace_api_url}}/api/v2/problems/{{ansible_eda.event.payload.eventId}}/comments"
      when: ansible_eda.event.payload.problemStatus == "OPEN"