---
-
  hosts: all
   -
      name: "Trigger CPU saturation"
      block:
        -
          name: "call easytravel configuration UI to apply configuration change"
          uri:
            url: "http://{{ easytravel_host }}:8079/services/ConfigurationService/setPluginEnabled?name={{ easytravel_plugin }}&enabled={{ easytravel_plugin_state }}"
            status_code: 202
        -
          name: "push Dynatrace custom configuration event"
          uri:
            url: "{{ dt_api_url }}/v1/events?Api-Token={{ dt_api_token }}"
            method: POST
            headers:
              content-type: application/json
            body:
              eventType: CUSTOM_CONFIGURATION
              attachRules:
                tagRule:
                - meTypes:
                  - SERVICE
                  - PROCESS_GROUP_INSTANCE
                  tags:
                  - context: CONTEXTLESS
                    key: Tier
                    value: "{{ configuration_tier }}"
              source: Ansible Automation Platform
              description: "{{ configuration_details }}"
              configuration: "{{ configuration_type }}"
              customProperties:
                Change Ticket: "{{ 99999999 | random(10000000, 10) }}"
                Change New: "{{ configuration_new }}"
                Change Old: "{{ configuration_old }}"
                Service Now: "https://demo.service-now.com/nav?uri=change_request.do?id=892eb1124"
            body_format: json
            status_code: 200